# Generated by Django 5.2.4 on 2025-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productoselectronicos_precio_oferta_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotienda',
            name='productos_favoritos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_favoritan', to='productos.productoselectronicos'),
        ),
    ]
