# Generated by Django 5.2.4 on 2025-07-22 17:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productoselectronicos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoselectronicos',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='productoselectronicos',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
