# Generated by Django 5.2.4 on 2025-07-15 21:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria_productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductosElectronicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(Decimal('0.01'))])),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_cantidad', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('especificaciones_tecnicas', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, help_text='Peso en kilogramos', max_digits=8, null=True)),
                ('dimensiones', models.CharField(blank=True, help_text='Formato: Alto x Ancho x Profundidad en cm', max_length=100)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'agotado'), ('descontinuado', 'Descontinuado'), ('preventa', 'pre-venta')], default='disponible', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoriaproducto')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Electrónico',
                'verbose_name_plural': 'Productos Electrónicos',
                'db_table': 'producto_electronico',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/imagenes/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.productoselectronicos')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'db_table': 'imagen_producto',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ResenaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha_resena', models.DateTimeField(auto_now_add=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='productos.productoselectronicos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña de Producto',
                'verbose_name_plural': 'Reseñas de Productos',
                'db_table': 'resena_producto',
                'ordering': ['-fecha_resena'],
            },
        ),
        migrations.AddIndex(
            model_name='productoselectronicos',
            index=models.Index(fields=['sku'], name='producto_el_sku_b54bff_idx'),
        ),
        migrations.AddIndex(
            model_name='productoselectronicos',
            index=models.Index(fields=['marca', 'modelo'], name='producto_el_marca_17e2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='productoselectronicos',
            index=models.Index(fields=['estado'], name='producto_el_estado_9c6868_idx'),
        ),
        migrations.AddIndex(
            model_name='productoselectronicos',
            index=models.Index(fields=['destacado'], name='producto_el_destaca_35ebf8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resenaproducto',
            unique_together={('producto', 'usuario')},
        ),
    ]
